### ISSUE TITLE
Regional Leaderboard Option

### ISSUE THREAD

**Issue by Dan1730** [Banalian/ExtraLeaderboardPositions#15]
Hi Banalian!

A while ago, I edited the code for this plugin to only show regional leaderboard positions for my region by having it store a list of all of the top 10,000 players on the map (IDs and region), and then filtering it by region. Obviously, this is very slow, but I was also able to keep a directory of matching player names and IDs in a new settings tab to have the leaderboard convert IDs to names and show the top 10 or top 20 players from my region by name. Although slow, I found it really fun and useful, but it quickly gets annoying to wait for it to refresh. Just wanted to throw the idea out there!

**Comment by Banalian** [comment]
Would you be open to opening a PR showing what you did to accomplish this ? I could definitely at least look into it, and check if using my API could help this process !

**Comment by Dan1730** [comment]
https://github.com/Banalian/ExtraLeaderboardPositions/pull/16

**Comment by Banalian** [comment]
Hi again :p, just coying my last message from the PR in case you see this at some point :p :

I'm still gonna need a bit more time to check it up, but in the meantime, could you change this so that there isn't a space after every line ? it makes the review pretty hard since the whole plugin is changed because of this 😅

**Comment by Banalian** [comment]
closing this since #16 was closed for now
