### ISSUE TITLE
Custom Colors!

### ISSUE THREAD

**Issue by MystWraith** [Banalian/ExtraLeaderboardPositions#19]
Hello!

I noticed that there was an option to show estimated medal positions, although this did not display for me. I think this is mainly related to the fact that many medals are beyond the accuracy allowed by this plugin.
I know that this is known, as the setting shows the disclaimer of "when possible".
If this could be expanded to show it ALWAYS, even if the accuracy is lost, like how floating point only has a finite number of significant digits.

The custom color idea then factors into this idea so that it could combine functionality similar to the Ultimate Medals plugin.
That way the colors could follow the medals (instead of 1, 10, 100, 1000 for auth, gold, silver, and bronze respectively). This could be interesting, and since there is champion medal integration, it could allow red to be a color.

Beyond this, I think that it would be fun to do custom colors (or even dynamically set to the color of the player skin average if tracking a friend/foe as seen in #11 ). Since custom benchmarks are included in the plugin already, it would be nice to show "as this color" or "above this color" and "below this color" as the default for below the max (like 10k).

**Comment by Banalian** [comment]
Hi !

Usually, the only reason a medal can't be displayed is if your pb on that map is better than the medal, and you aren't using the external API to refresh the leaderboard (Because in that case, the Nadeo API returns some wrong data if I try to get that information). Is there another case were that's not working ? if so, that might be a bug :p

Generally speaking, reworking the colors to have custom preset or at least a new mode for the medals is something I wanted to do at some point, I just never took to the time to work on that feature. I'll definitively check it out again now that I have more free time !

**Comment by MystWraith** [comment]
I did find the external API feature and that did fix the problem, but it was confusing as to why that worked. Thanks for the clarification.

Good to know the colors idea has already been thought of!
